---
- name: Read time zone
  ansible.builtin.command: timedatectl show
  register: timedate_show
  changed_when: false

- name: Create timezone file for openhab
  ansible.builtin.copy:
    content: "{{ timedate_show.stdout_lines[0].split('=')[1] }}"
    dest: /etc/timezone
    mode: "0644"

- name: Setup localtime
  ansible.builtin.file:
    state: link
    src: /usr/share/zoneinfo/{{ openhab_localtime }}
    dest: /etc/localtime

- name: Ensure openhab folders are present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0700
    owner: root
    group: root
  loop: "{{ __openhab_dirs }}"

- name: Set devices podman option variable
  when: openhab_additional_device != ""
  ansible.builtin.set_fact:
    __openhab_podman_device_string: "--device=/dev/{{ openhab_additional_device }}"

- name: Add openhab systemd service file
  ansible.builtin.template:
    src: openhab.service.j2
    dest: /etc/systemd/system/openhab.service
    mode: "0644"
  register: openhab_service_file
  notify:
    - Restart openhab

- name: Ensure openhab service is started
  ansible.builtin.systemd:
    name: openhab
    state: started
    enabled: true

- name: Configure firewall rules
  when: openhab_configure_firewall
  block:
    - name: Get firewalld status
      ansible.builtin.systemd:
        name: firewalld
      register: firewalld_service

    - name: Enable openHAB ports
      when: firewalld_service.status.ActiveState == 'active'
      ansible.posix.firewalld:
        port: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      loop:
        - 8883/tcp
        - 8888/tcp
      tags: firewalld
