---
# tasks file for backup
- name: Install rpm packages on ostree based os
  community.general.rpm_ostree_pkg:
    name:
      - rsync
      - restic
    state: present
  notify: Reboot linux server

- name: Call handlers
  ansible.builtin.meta: flush_handlers

# Ensure Backup user exists
- name: Create linux user named backup
  ansible.builtin.user:
    name: "{{ backup_server_user }}"
    comment: Backup user
    shell: /bin/bash
    state: present
    generate_ssh_key: true
# Finally Configure restic to backup all dirs to synology
